---
title: "Lista 2 resolvida"
author: "Probabilidade 1"
date: 'monitor: Eduardo Freire'
output:
  pdf_document: default
  html_document:
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1 - Se $A \subset B$ então o evento $B$ pode ser particionado em: $B = (B\cap A) \cup (B\cap A^c) = A \cup (B\cap A^c)$

Lembre que pelo axioma 2, qualquer probabilidade é maior ou igual a zero, ou seja, $P(B\cap A^c) \geq 0$

Então, como a união é disjunta, segue que $P(B)= P(A) + P(B\cap A^c) \geq P(A)$. 



2 - Use a dica para escrever $P(\bigcup\limits_{i=1}^{\infty} A_i)$ como a união de uma sequência disjunta de eventos. Agora lembre do axioma 3 de Kolmogorov: Para toda sequência $A_1, A_2, ... \in \mathcal{F}$, mutuamente exclusivos, onde $\mathcal{F}$ é $\sigma$-algebra de subconjuntos de $\Omega$:

$P(\bigcup\limits_{i=1}^{\infty} A_i) = \sum\limits_{i=1}^{\infty} P(A_i)$

Por meio desse axioma, podemos escrever:

$P(\bigcup\limits_{i=1}^{\infty} A_i) = P(A_1) + P(A_1^{c}\cap A_2) + p(A_1^{c}\cap A_2^{c} \cap A_3) + ...$

como, para qualquer j, $A_1^{c}\cap A_2^{c} \cap .. \cap A_{j-1}^{c} \cap A{j} \subset A_j$, então, pelo resultado do exercício 1, segue que:

$P(\bigcup\limits_{i=1}^{\infty} A_i) \leq P(A_1) + P(A_2) + P(A_3) + ...$

3 - Defina os eventos A: "Álvaro ganha", B: "Bené ganha", C:"Cidinha ganha", K:"É corrupto"

Como pelo Axioma 1 de Kolmogorov a soma de todas as probabilidades deve ser igual a 1:

$$ P(A) + P(B) + P(C) = 1 $$

$P(A) = \frac{2}{5}$ \ $P(B) = \frac{1}{5}$  \ $P(C) = \frac{2}{5}$

$P(A|K) = \frac{1}{5}$ \ $P(B|K) = \frac{1}{10}$ \ $P(C|K) = \frac{1}{5}$


a)  Como o fato de não ser corrupto não afeta a probabilidade inicial, e como os eventos abaixo são disjuntos:

$$P(A|K) \cup P(C|K^c) = P(A|K) \cup P(C) $$
    
$$P(A|K) + P(C) = 0.5 \times 0.4 + 0.4 = 0.6$$


b) Desconsiderei essa questão na correção, pois existe a possibilidade de mais de uma interpretação, onde é possível confundir as probabilidades à priori com as condicionais. Abaixo a solução esperada:

Lembre de probabilidade condicional para fazer esse exercício.

$$P(K|B) = \frac{P(K \cap B)}{P(B)}$$

$$P(K|B) = \frac{P(B|K)P(K)}{P(B)}  $$

$$P(K|B) = \frac{0.1 \times 0.42}{0.2 } = 0.21  $$


4 - S: "é spam", F:"tem a frase"

$P(S) = 0.8$ \ $P(F|S) = 0.1$ \ $P(F|S^c) = 0.01$

$$P(S|F) = \frac{P(F|S)P(S)}{P(F|S)P(S) + P(F|S^c)P(S^c) }  $$



$$ \frac{0.1 \times 0.8}{0.1 \times 0.8 + 0.01 \times 0.2 } = 0.975 $$

5 - A: "o oponente é iniciante" \ B: "o oponente é intermediário" \ C: "o oponente é avançado" \ "G: "ganhar"

P(G|A) = $\frac{9}{10}$ \ P(G|B) = $\frac{1}{2}$ \ P(G|C) = $\frac{3}{10}$

$P(A) = P(B) = P(C) = \frac{1}{3}$


a) Pela Lei da Probabilidade Total:

$$ P(G) = P(G \cap A) \cup P(G \cap B) \cup P(G \cap C) $$


$$ P(G) = P(G|A)P(A) + P(G|B)P(B) + P(G|C)P(C) $$

$$ P(G) = \frac{9}{10} \times \frac{1}{3} + \frac{1}{2} \times \frac{1}{3} + \frac{3}{10} \times \frac{1}{3} = \frac{34}{60} = 0.566666 \approx 0.57$$

b) Seja $G_1$ o evento em que se ganha o primeiro jogo contra um oponente e $G_2$ o segundo jogo em que se ganha contra o mesmo oponente



$$ P(G_2 | G_1) = \frac{P(G_2\cap G_1)}{P(G_1)} $$


Como os resultados dos jogos são independentes, $P(G_2\cap G_1) = P(G_1)  P(G_2)$


Logo:

$$ P(G_2 | G_1) = \frac{P(G_1)P(G_2)}{P(G_1)} $$



$$ P(G_2 | G_1) = P(G_2)$$

Como a questão pede a probabilidade de vencer o primeiro e o segundo jogo, poderíamos ter parado na interseção, sem ter visto a condicional.


Assim fica a resposta:

$$ P(G_2\cap G_1) = P(G_1)  P(G_2) $$
$$ P(G_2\cap G_1) = 0.57 \times  0.57 = 0.3249   $$

