---
title: "Luis Henrique C. P. Toledo"
output: html_notebook
---


```{r}
#################### QUESTÃO 1 ###################################

df<-read.csv("dados.txt")
df<-df[,-1]
y<-df[,1]
x <-cbind(rep(1,40),df[,-1])
x<-as.matrix(x)
colnames(x)[1]<-"Intercepto"
b <- matrix(c(3,1,2,2,1,3,4),7,1)
erro <- 10^(-11) 
it = 0
k = 1000

while (k>erro & it<1001) {
 it=it+1
 bant=b
 eta=x%*%bant
 mi=eta
 der=rep(1,40)
 v=mi^2
 w=diag(c((1/der)^2/v))
 z=eta+((y-mi)*der)
 b=solve(t(x)%*%w%*%x)%*%t(x)%*%w%*%z
 k=sum(((bant-b)/bant)^2)
 mtinf<-t(x)%*%w%*%x
}
b



```

```{r}

############## QUESTÃO 2 ###############################
invmtinf<-solve(mtinf)
raizinvmtinf<- sqrt(diag(invmtinf))[-1]
LI<-b[-1]-qnorm(0.975)*raizinvmtinf
LS<-b[-1]+qnorm(0.975)*raizinvmtinf
LI
LS


```

```{r}
###### QUESTÃO 3 ###########
x2 <-cbind(rep(1,40),df[,2])
x2<-as.matrix(x2)
b2 <- matrix(c(0,2),2,1)
erro2 <- 10^(-11) 
it2 = 0
k2 = 1000

while (k2>erro2 & it2<1001) {
 it2=it2+1
 bant2=b2
 eta2=x2%*%bant2
 mi2=eta2
 der2=rep(1,40)
 v2=mi2^2
 w2=diag(c((1/der2)^2/v2))
 z2=eta2+((y-mi2)*der2)
 b2=solve(t(x2)%*%w2%*%x2)%*%t(x2)%*%w2%*%z2
 k2=sum(((bant2-b2)/bant2)^2)
 mtinf2<-t(x2)%*%w2%*%x2
}
b2

```

```{r}
#####   QUESTÃO 4 #####

par1<-sum(log(x%*%b))
par2<- sum(y/(x%*%b))

par3<-sum(log(x2%*%b2))
par4<-sum(y/(x2%*%b2)) 

dev1<- 2*(-sum(log(y))-40+par1+par2)
dev2<-2*(-sum(log(y))-40+par3+par4)
dev1
dev2

```

```{r}
######QUESTÃO 5 ##############

Dif<- dev2-dev1
# sob Ho dif(variação da deviance) tem distribuição Qui-quadrado com 5 G.L
#achar o quantil dessa Qui-quadrado.

1- pchisq(Dif,5)

#Ao nível de 5% de significancia não há evidencia estatística para rejeitar a hipótese nula de que o modelo maior explica tão bem os dados quanto o modelo menor.


```

